[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
mypy = "==0.790"
pytest = "==4.3.1"
pytest-django = "==3.4.5"
flake8 = "==3.8.4"
pytest-cov = "==2.6.1"
python-dotenv = "==0.9.1"
factory-boy = "==2.11.1"
requests-mock = "==1.5.2"
django-webtest = "==1.9.7"
freezegun = "==0.3.12"
black = "==22.3.0"
debugpy = "==1.2.1"

[packages]
django = "==3.2.13"
whitenoise = "==5.2.0"
dj-database-url = "==0.5.0"
django-csp = "==3.7"
gunicorn = "==19.9.0"
psycopg2-binary = "==2.8.4"
graphene-django = "==2.15.0"
graphene = "==2.1.7"
graphql-core = "==2.2.1"
pydantic = "==1.6.2"
requests = "==2.25.1"
urllib3 = "==1.26.5"
rollbar = "==0.14.5"
twilio = "==6.18.0"
boto3 = "==1.17.48"
django-storages = "==1.11.1"
zeep = "==3.1.0"
pyotp = "==2.2.7"
rapidpro-python = "==2.7.1"
lob = "==4.0.0"
graphql-relay = "==2.0.1"
celery = "==4.3.0"
django-celery-results = "==1.1.2"
dj-email-url = "==0.2.0"
docusign-esign = "==3.7.1"
pypdf2 = "==1.26.0"
mailchimp3 = "==3.0.14"
django-sql-dashboard = "==1.0.1"

# As of 2021-02-01, this *cannot* be version 2.x because docusign-esign is
# incompatible with it: https://github.com/docusign/docusign-python-client/issues/94
pyjwt = "==1.7.1"

[requires]
python_version = "3.8.2"
