# Generated by Django 3.2 on 2021-05-21 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texting', '0006_alter_phonenumberlookup_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='err_code',
            field=models.IntegerField(blank=True, help_text='The error code encountered when we attempted to send the reminder, if any.If the reminder was sent successfully, this will be null.  Note that this error should reflect a reason for the reminder to not be sent at all--it should *not* represent a temporary error such as a networking error, where we would want to retry sending the message after some time.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='kind',
            field=models.TextField(choices=[('LOC', 'Letter of complaint reminder'), ('NORENT_CA_2020_11', 'NoRent California reminder - November 2020'), ('NORENT_CA_2020_12', 'NoRent California reminder - December 2020'), ('NORENT_CA_2021_01', 'NoRent California reminder - January 2021'), ('NORENT_CA_2021_02', 'NoRent California reminder - February 2021'), ('NORENT_CA_2021_03', 'NoRent California reminder - March 2021'), ('NORENT_CA_2021_04', 'NoRent California reminder - April 2021'), ('NORENT_CA_2021_05', 'NoRent California reminder - May 2021'), ('NORENT_CA_2021_06', 'NoRent California reminder - June 2021')], help_text='The type of reminder we attempted to send.', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sent_at',
            field=models.DateField(help_text='When we attempted to send the reminder.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sid',
            field=models.CharField(blank=True, help_text='The Twilio Message SID for the reminder, if we sent it. If an error occurred, this will be a blank string.', max_length=34),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(help_text='The user whom we attempted to send the reminder to.', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
